version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: fsw-barber-db
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-fsw-barber}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
